### ISSUE TITLE
Migrate project and output to ESM

### ISSUE THREAD

**Issue by Jaid** [Jaid/epoch-seconds#77]
Migrate this package to ES Modules.

Resources:

- https://nodejs.org/api/esm.html
- https://webpack.js.org/guides/ecma-script-modules
- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
- [Webpack project ESM](https://github.com/webpack/webpack/projects/8)

**Comment by Jaid** [comment]
`npm run build:prod` output:

```
[webpack-cli] Error: For the selected environment is no default script chunk format available:
JSONP Array push can be chosen when 'document' or 'importScripts' is available.
CommonJs exports can be chosen when 'require' or node builtins are available.
Make sure that your 'browserslist' includes only platforms that support these features or select an appropriate 'target' to allow selecting a chunk format by default. Alternatively specify the 'output.chunkFormat' directly.
    at P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\config\defaults.js:669:11
    at F (P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\config\defaults.js:71:15)
    at applyOutputDefaults (P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\config\defaults.js:650:2)
    at applyWebpackOptionsDefaults (P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\config\defaults.js:182:2)
    at createCompiler (P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\webpack.js:78:2)
    at create (P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\webpack.js:127:16)
    at webpack (P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\webpack.js:135:47)
    at WebpackCLI.f [as webpack] (P:\Git\epoch-seconds-issue-77\node_modules\webpack\lib\index.js:55:16)
    at WebpackCLI.createCompiler (P:\Git\epoch-seconds-issue-77\node_modules\webpack-cli\lib\webpack-cli.js:2053:29)
    at WebpackCLI.buildCommand (P:\Git\epoch-seconds-issue-77\node_modules\webpack-cli\lib\webpack-cli.js:2173:20)
```

**Comment by Jaid** [comment]
Current final Webpack options:

```
amd: undefined,
bail: undefined,
cache: undefined,
context: 'P:\\Git\\epoch-seconds-issue-77',
dependencies: undefined,
devServer: undefined,
devtool: 'source-map',
entry: { main: { import: [ 'P:\\Git\\epoch-seconds-issue-77\\src' ] } },
experiments: {},
externals: [Function (anonymous)],
externalsPresets: {},
externalsType: undefined,
ignoreWarnings: undefined,
infrastructureLogging: {
  stream: <ref *1> WriteStream {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      constructed: true,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      readable: false,
      [Symbol(kPaused)]: null
    },
    _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
    _eventsCount: 1,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: null,
    _server: null,
    columns: 160,
    rows: 23,
    _type: 'tty',
    fd: 2,
    _isStdio: true,
    destroySoon: [Function: destroy],
    _destroy: [Function: dummyDestroy],
    [Symbol(async_id_symbol)]: 4,
    [Symbol(kHandle)]: TTY { [Symbol(owner_symbol)]: [Circular *1] },
    [Symbol(kSetNoDelay)]: false,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesRead)]: 0,
    [Symbol(kBytesWritten)]: 0
  },
  level: 'info',
  debug: false,
  colors: true,
  appendOnly: false
},
loader: {},
mode: 'production',
module: {
  noParse: undefined,
  unsafeCache: undefined,
  parser: {
    javascript: {
      unknownContextRequest: undefined,
      unknownContextRegExp: undefined,
      unknownContextRecursive: undefined,
      unknownContextCritical: undefined,
      exprContextRequest: undefined,
      exprContextRegExp: undefined,
      exprContextRecursive: undefined,
      exprContextCritical: undefined,
      wrappedContextRegExp: undefined,
      wrappedContextRecursive: undefined,
      wrappedContextCritical: undefined,
      strictExportPresence: undefined,
      strictThisContextOnImports: undefined
    }
  },
  generator: {},
  defaultRules: undefined,
  rules: [
    { test: /\.(js|jsx|ts|tsx)$/, oneOf: [ [Object], [Object] ] },
    { test: /\.(yaml|yml)$/, loader: 'yml-loader' },
    { test: /\.lines$/, loader: 'lines-loader' },
    {
      test: /\.rlines$/,
      loader: 'lines-loader',
      options: { sort: true, random: true }
    },
    { test: /\.txt$/, loader: 'raw-loader' },
    { test: /\.(hbs|handlebars)$/, oneOf: [ [Object], [Object] ] }
  ]
},
name: undefined,
node: {},
optimization: {
  minimizer: [
    TerserPlugin {
      options: {
        test: /\.[cm]?js(\?.*)?$/i,
        extractComments: false,
        parallel: true,
        include: undefined,
        exclude: undefined,
        minify: undefined,
        terserOptions: [Object]
      }
    }
  ],
  runtimeChunk: undefined,
  splitChunks: { defaultSizeTypes: [ '...' ], cacheGroups: {} },
  emitOnErrors: undefined
},
output: {
  assetModuleFilename: undefined,
  charset: undefined,
  chunkFilename: undefined,
  chunkFormat: undefined,
  chunkLoading: undefined,
  chunkLoadingGlobal: undefined,
  chunkLoadTimeout: undefined,
  clean: undefined,
  compareBeforeEmit: undefined,
  crossOriginLoading: undefined,
  devtoolFallbackModuleFilenameTemplate: undefined,
  devtoolModuleFilenameTemplate: undefined,
  devtoolNamespace: undefined,
  environment: {},
  enabledChunkLoadingTypes: [ '...' ],
  enabledLibraryTypes: [ '...' ],
  enabledWasmLoadingTypes: [ '...' ],
  filename: 'index.js',
  globalObject: 'this',
  hashDigest: undefined,
  hashDigestLength: undefined,
  hashFunction: undefined,
  hashSalt: undefined,
  hotUpdateChunkFilename: undefined,
  hotUpdateGlobal: undefined,
  hotUpdateMainFilename: undefined,
  iife: undefined,
  importFunctionName: undefined,
  importMetaName: undefined,
  scriptType: undefined,
  library: {
    type: 'umd2',
    auxiliaryComment: undefined,
    export: undefined,
    name: 'epochSecondsIssue77',
    umdNamedDefine: undefined
  },
  module: undefined,
  path: 'P:\\Git\\epoch-seconds-issue-77\\dist\\package\\production',
  pathinfo: undefined,
  publicPath: undefined,
  sourceMapFilename: undefined,
  sourcePrefix: undefined,
  strictModuleExceptionHandling: undefined,
  trustedTypes: undefined,
  uniqueName: undefined,
  wasmLoading: undefined,
  webassemblyModuleFilename: undefined,
  workerChunkLoading: undefined,
  workerWasmLoading: undefined
},
parallelism: undefined,
performance: { maxEntrypointSize: 4000000, maxAssetSize: 4000000 },
plugins: [
  CLIPlugin {
    options: {
      configPath: 'P:\\Git\\epoch-seconds-issue-77\\webpack.config.babel.js',
      helpfulOutput: true,
      hot: undefined,
      progress: undefined,
      prefetch: undefined,
      analyze: undefined
    },
    logger: WebpackLogger {
      getChildLogger: [Function (anonymous)],
      [Symbol(webpack logger raw log method)]: [Function (anonymous)]
    }
  },
  LoaderOptionsPlugin {
    options: {
      debug: false,
      minimize: true,
      test: { test: [Function: test] }
    }
  },
  CleanWebpackPlugin {
    dangerouslyAllowCleanPatternsOutsideProject: false,
    dry: false,
    verbose: false,
    cleanStaleWebpackAssets: true,
    protectWebpackAssets: true,
    cleanAfterEveryBuildPatterns: [],
    cleanOnceBeforeBuildPatterns: [ 'P:\\Git\\epoch-seconds-issue-77\\dist\\packa
    currentAssets: [],
    initialClean: false,
    outputPath: 'P:\\Git\\epoch-seconds-issue-77\\dist\\package\\production',
    apply: [Function: bound apply],
    handleInitial: [Function: bound handleInitial],
    handleDone: [Function: bound handleDone],
    removeFiles: [Function: bound removeFiles]
  },
  b {
    options: {
      htmlOutputDir: null,
      tsdOutputFile: null,
      readmePath: null,
      packagePath: null,
      jsdocConfig: {},
      jsdocHtmlConfig: {},
      jsdocTsdConfig: {},
      productionOnly: true,
      injectTsdExports: true,
      babel: false
    }
  },
  CleanWebpackPlugin {
    dangerouslyAllowCleanPatternsOutsideProject: false,
    dry: false,
    verbose: false,
    cleanStaleWebpackAssets: true,
    protectWebpackAssets: true,
    cleanAfterEveryBuildPatterns: [],
    cleanOnceBeforeBuildPatterns: [
      'P:\\Git\\epoch-seconds-issue-77\\dist\\package\\homepage',
      'P:\\Git\\epoch-seconds-issue-77\\dist\\package\\tsd'
    ],
    currentAssets: [],
    initialClean: false,
    outputPath: 'P:\\Git\\epoch-seconds-issue-77\\dist\\package\\production',
    apply: [Function: bound apply],
    handleInitial: [Function: bound handleInitial],
    handleDone: [Function: bound handleDone],
    removeFiles: [Function: bound removeFiles]
  },
  D {
    options: {
      publishimo: [AsyncFunction (anonymous)],
      filename: 'package.json',
      format: false,
      autoMain: true,
      autoTypes: true,
      banner: false,
      unicodeCopyright: true,
      productionOnly: true,
      debugFolder: null,
      incudeFields: [],
      excludeFields: [],
      json5: false,
      autoExclude: false,
      includeDefaultBinName: true
    }
  },
  d { options: { defaultLicense: 'MIT' } },
  CopyPlugin {
    patterns: [
      { from: 'readme.*', noErrorOnMissing: true },
      { from: 'license.*', noErrorOnMissing: true }
    ],
    options: {}
  },
  LicenseWebpackPlugin {
    pluginOptions: {
      renderLicenses: [Function: Ye],
      outputFilename: 'thirdPartyLicenses.txt',
      perChunkOutput: false
    }
  },
  IgnorePlugin {
    options: { resourceRegExp: /^\.\/locale$/, contextRegExp: /moment$/ },
    checkIgnore: [Function: bound checkIgnore]
  },
  PkgBannerPlugin {}
],
profile: undefined,
recordsInputPath: undefined,
recordsOutputPath: undefined,
resolve: {
  extensions: [ '.js', '.jsx', '.ts', '.tsx', '.json', '.yml' ],
  byDependency: {}
},
resolveLoader: {},
snapshot: {
  resolveBuildDependencies: undefined,
  buildDependencies: undefined,
  resolve: undefined,
  module: undefined,
  immutablePaths: undefined,
  managedPaths: undefined
},
stats: {
  all: false,
  assets: true,
  assetsSort: '!size',
  excludeAssets: /.(map|d.ts)$/,
  colors: true,
  warnings: true,
  errors: true,
  errorDetails: true
},
target: undefined,
watch: undefined,
watchOptions: {}
```

**Comment by Jaid** [comment]
Giving up for now. Too early to migrate.

Waiting for new progress here:
- https://github.com/webpack/webpack/projects/8
- https://github.com/webpack/webpack/issues/2933#issuecomment-774253975

**Comment by Jaid** [comment]
Nevermind, I'll give it another try.

This is an important fix:
https://github.com/webpack/webpack/releases/tag/v5.52.0

**Comment by Jaid** [comment]
### Migration step
Rename “.babelrc.js” to “.babelrc.json”, replace content by JSON:

```json
{
  "presets": [
    "jaid"
  ]
}
```

**Comment by Jaid** [comment]
### Migration step

Rename “jest.config.js” to “jest.config.json”, replace content by JSON:

```json
{
  "testEnvironment": "node",
  "coverageDirectory": "<rootDir>/dist/jest/coverage",
  "collectCoverageFrom": [
    "<rootDir>/dist/package/development/**",
    "!<rootDir>/node_modules/"
  ],
  "coverageReporters": [
    "text-summary",
    "html"
  ],
  "testPathIgnorePatterns": [
    "<rootDir>/node_modules/",
    "<rootDir>/dist/"
  ],
  "modulePathIgnorePatterns": [
    "<rootDir>/dist",
    "<rootDir>/build"
  ],
  "moduleNameMapper": {
    "^root": "<rootDir>",
    "^src": "<rootDir>/src",
    "^lib": "<rootDir>/src/lib"
  }
}
```

**Comment by Jaid** [comment]
### Migration step

Rename “.eslint.js” to “.eslintrc.json”, replace content by JSON:

```json
{
  "extends": [
    "jaid"
  ]
}
```

**Comment by Jaid** [comment]
Files containing top-level awaits are currently skipped by ESLint, being fixed in ESLint v8.

https://github.com/eslint/eslint/issues/14632

**Comment by Jaid** [comment]
### Migration step

Rewrite “debug” creation.

From:
```js
const debug = require("debug")(process.env.REPLACE_PKG_NAME)
```

To:
```js
import createDebug from "debug"
const debug = createDebug(process.env.REPLACE_PKG_NAME)
```

**Comment by Jaid** [comment]
### Migration step

From:
```js
const dirName = __dirname
```
To:
```js
import path from "node:path"
import {fileURLToPath} from "node:url"

const dirName = path.dirname(fileURLToPath(import.meta.url))
```

**Comment by Jaid** [comment]
Example commit for migrating config files:
https://github.com/Jaid/epoch-seconds/commit/c6de87e71f08a9f3721e55f2a8ec650c6fa13aca
